import { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowRight, Bell, BookOpen, ChevronRight, Download, ExternalLink, LoaderCircle, Plus, RefreshCw, ShieldCheck, Sparkles, Trash2 } from 'lucide-react';
import PriceChart from './PriceChart';
import { dateTime, number, percent, tone } from './format';
import type { Dashboard, Job, News, Stock } from './types';

interface Props {
  data: Dashboard | null; loading: boolean; catalog: Stock[]; snapshots: Record<string, Dashboard>; watchlist: string[];
  savingWatch: boolean; code: string; setCode: (code: string) => void; userSignedIn: boolean; add: () => void; remove: (code: string) => void;
  running: boolean; job: Job | null; collect: (days: number, community: boolean) => void; audit: () => void; auditLoading: boolean;
  openAssistant: (news?: News) => void; briefing: () => void;
}

export default function ResearchDashboard(props: Props) {
  const { data, loading, catalog, snapshots, watchlist, savingWatch, code, setCode, userSignedIn, add, remove, running, job, collect, audit, auditLoading, openAssistant, briefing } = props;
  const [mode, setMode] = useState('近 3 月');
  const [indicator, setIndicator] = useState('成交量');
  const [period, setPeriod] = useState('日 K');
  const [includeCommunity, setIncludeCommunity] = useState(false);
  const [days, setDays] = useState(30);
  const [filter, setFilter] = useState('全部');
  useEffect(() => setFilter('全部'), [code]);
  const currentBar = data?.candles.at(-1);
  const analyzed = data?.news.filter(row => row.score != null) ?? [];
  const mean = analyzed.length ? analyzed.reduce((sum, row) => sum + row.score!, 0) / analyzed.length : null;
  const visible = data?.news.filter(row => filter === '全部' || (filter === '利好' ? (row.score ?? 0) > 0 : filter === '利空' ? (row.score ?? 0) < 0 : filter === '待研判' ? row.score == null : row.score === 0)) ?? [];
  const openEvent = useCallback((id: string) => { const news = data?.news.find(row => row.id === id); if (news) openAssistant(news); }, [data, openAssistant]);
  function exportNews() {
    if (!data) return;
    const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }));
    const link = document.createElement('a'); link.href = url; link.download = `finpulse-${code}.json`; link.click(); URL.revokeObjectURL(url);
  }
  return <div className="finance-layout">
    <aside className="portfolio-rail"><section className="panel portfolio-panel"><header><h2>我的自选</h2><button aria-label="添加自选股" className="icon-button" onClick={add}><Plus size={17} /></button></header><p className="rail-caption">{userSignedIn ? '保存在你的账号中' : '登录后保存自选股'}</p>{watchlist.map(stockCode => { const stock = catalog.find(row => row.code === stockCode); const snapshot = snapshots[stockCode]; return stock && <div key={stockCode} className={`portfolio-row ${code === stockCode ? 'active' : ''}`}><button onClick={() => setCode(stockCode)}><span><strong>{stock.name}</strong><small>{stock.exchange} {stock.code}</small></span><span><strong className="mono">{number(snapshot?.stock.price)}</strong><small className={tone(snapshot?.stock.change ?? null)}>{percent(snapshot?.stock.change)}</small></span></button><button className="remove-stock" aria-label={`移除${stock.name}`} disabled={savingWatch} onClick={() => remove(stockCode)}><Trash2 size={12} /></button></div>; })}{watchlist.length === 0 && <p className="rail-empty">还没有自选股，点击加号添加。</p>}<button className="add-watch" onClick={add}><Plus size={14} />管理关注标的</button></section><section className="rail-note"><ShieldCheck size={17} /><h3>研究有据可查</h3><p>新闻保留原文和清洗记录。行情展示数据日期，模型研判保留推断局限。</p><button onClick={briefing}>查看自选股早报<ArrowRight size={14} /></button></section></aside>
    <div className="research-main-column">
      {loading && <div className="panel empty-card"><LoaderCircle className="spin" size={25} /><p>正在读取已保存的数据…</p></div>}
      {data && <>
        <section className="panel live-quote"><header><div><span className="industry-tag">{data.stock.industry}</span><h2>{data.stock.name}<small>{data.stock.exchange}:{data.stock.code}</small></h2><p>{data.quote.source ?? '尚未采集行情'} · {data.quote.as_of_date ?? '—'} · {data.quote.status === 'stale' ? '上次保存的日线，本次更新失败' : '非实时价格'}</p></div><button className="subtle-button" onClick={add}>切换标的<ChevronRight size={14} /></button></header><div className="live-price-row"><div><strong className={`mono ${tone(data.stock.change)}`}>{number(data.stock.price)}</strong><span className={tone(data.stock.change)}>{percent(data.stock.change)}<small>较前一返回交易日</small></span></div><dl><div><dt>开盘</dt><dd>{number(currentBar?.open)}</dd></div><div><dt>最高</dt><dd>{number(currentBar?.high)}</dd></div><div><dt>最低</dt><dd>{number(currentBar?.low)}</dd></div><div><dt>成交量</dt><dd>{currentBar ? `${(currentBar.volume / 10000).toFixed(1)} 万股` : '—'}</dd></div></dl></div><div className="live-chart-toolbar"><div className="segmented">{['近 1 月', '近 3 月', '全部'].map(item => <button key={item} className={mode === item ? 'active' : ''} onClick={() => setMode(item)}>{item}</button>)}</div><select aria-label="K线周期" value={period} onChange={e => setPeriod(e.target.value)}><option>日 K</option><option>周 K</option></select><span>MA5 / MA10 / MA20</span></div>{data.candles.length ? <PriceChart candles={data.candles} news={data.news} mode={mode} period={period} indicator={indicator} onEvent={openEvent} /> : <div className="chart-empty"><Activity size={32} /><h3>让真实行情进入你的看板</h3><p>点击下方「采集并分析」，获取历史日线与近期新闻。</p></div>}<footer className="chart-footer"><div className="indicator-switch">{['成交量', 'MACD', 'RSI'].map(item => <button key={item} className={indicator === item ? 'active' : ''} onClick={() => setIndicator(item)}>{item}</button>)}</div><span>新闻日期标记 · 点击查看原文与研判</span></footer></section>
        <section className="pipeline-bar"><div><span className={`status-dot ${running ? 'pending' : ''}`} /><strong>{running ? job?.stage ?? '正在提交任务…' : job?.status === 'failed' ? '本次任务失败' : '真实新闻研究'}</strong><small>{running ? '可继续浏览，任务在后端执行' : `最近保存：${dateTime(data.as_of)}`}</small></div><div className="pipeline-options"><select aria-label="新闻检索区间" value={days} onChange={e => setDays(+e.target.value)} disabled={running}><option value={7}>近 7 天</option><option value={30}>近 30 天</option><option value={90}>近 90 天</option></select><label><input type="checkbox" checked={includeCommunity} onChange={e => setIncludeCommunity(e.target.checked)} disabled={running} />含社区样本</label><button className="primary-button" disabled={running} onClick={() => collect(days, includeCommunity)}>{running ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />}{running ? '正在处理' : '采集并分析'}</button></div></section>
        {job?.warnings.length ? <div className="pipeline-warning" role="status">本次任务：{job.warnings.join('；')}</div> : null}
        {data.pipeline && <div className="pipeline-summary"><span>检索 {data.pipeline.counts.input}</span><ChevronRight size={12} /><span>保留 {data.pipeline.counts.retained}</span><ChevronRight size={12} /><span>合并 {data.pipeline.counts.merged}</span><ChevronRight size={12} /><span>本轮研判 {data.pipeline.counts.analyzed}</span><button disabled={auditLoading} onClick={audit}>{auditLoading ? '读取中…' : '查看清洗记录'}</button></div>}
        {!!data.pipeline?.warnings.length && !job && <details className="pipeline-warning"><summary>数据采集存在 {data.pipeline.warnings.length} 项限制</summary>{data.pipeline.warnings.map(item => <p key={item}>{item}</p>)}</details>}
        <section className="panel live-news"><header><div><p className="eyebrow">LATEST COVERAGE</p><h2>{data.stock.name} · 新闻与研判<span>{data.news.length}</span></h2></div><button className="icon-button" aria-label="导出当前研究数据" onClick={exportNews}><Download size={17} /></button></header><div className="news-tabs">{['全部', '利好', '中性', '利空', '待研判'].map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div>{visible.length ? <div className="live-news-list">{visible.map((news, index) => <article className={index === 0 ? 'feature-news' : ''} key={news.id}><div className="news-kicker"><span>{news.source}</span><time>{news.time}</time><span>{news.tag}</span><span className={`news-score ${news.score == null ? 'unrated' : news.score > 0 ? 'up' : news.score < 0 ? 'down' : ''}`}>{news.score == null ? '待研判' : `AI ${news.score > 0 ? '+' : ''}${news.score}`}</span></div><h3><a href={news.url} target="_blank" rel="noopener noreferrer">{news.title}<ExternalLink size={13} /></a></h3><p>{news.analysis?.summary ?? news.content.slice(0, 190)}</p>{news.analysis && <div className="news-chain">{news.analysis.causal_chain.map((step, i) => <span key={i}>{i > 0 && <ChevronRight size={12} />}{step}</span>)}</div>}<div className="news-actions"><span>{news.text_source === 'extracted_body' ? '已提取正文' : '搜索片段'} · {news.date_status === 'body_verified' ? '正文日期已核对' : '来源元数据日期'}{news.sources.length > 1 ? ` · ${news.sources.length} 个合并来源` : ''}</span><button onClick={() => openAssistant(news)}><Sparkles size={14} />{news.analysis ? '查看研判 / 追问' : '生成 AI 研判'}<ArrowRight size={13} /></button></div>{news.analysis_error && <p className="news-analysis-error">研判失败：{news.analysis_error}</p>}</article>)}</div> : <div className="empty-card"><BookOpen size={27} /><h3>{data.news.length ? '该分类暂无新闻' : '尚无通过清洗的新闻'}</h3><p>{data.news.length ? '试试其他筛选条件。' : '发起采集后，只有来源、日期和内容通过校验的新闻才会进入列表。'}</p></div>}</section>
        <section className="panel returns-panel"><header><h2>新闻后的历史走势</h2><span>事后观察</span></header>{data.backtest.items.length ? <div className="returns-table"><table><thead><tr><th>新闻</th><th>基准日</th><th>3 交易日</th><th>5 交易日</th></tr></thead><tbody>{data.backtest.items.slice(0, 8).map(item => <tr key={item.news_id}><td>{item.title}</td><td>{item.base_date ?? '待有日线'}</td><td className={tone(item.return_3d)}>{percent(item.return_3d)}</td><td className={tone(item.return_5d)}>{percent(item.return_5d)}</td></tr>)}</tbody></table></div> : <p className="returns-note">保存新闻与日线后，这里会展示可计算的后续价格变化。</p>}<p className="returns-note">{data.backtest.note}</p></section>
      </>}
    </div>
    <aside className="research-right-rail"><section className="panel research-overview"><span className="eyebrow">RESEARCH AT A GLANCE</span><h2>消息面概览</h2><div className="overview-score"><strong>{mean == null ? '—' : mean.toFixed(1)}</strong><span>/ 2<small>已研判新闻平均分</small></span></div><div className="overview-stats"><span><strong>{data?.news.length ?? 0}</strong>保留新闻</span><span><strong>{analyzed.length}</strong>已完成研判</span></div><p>仅反映当前新闻样本。全市场恐慌与贪婪指数尚未接入，不以新闻评分替代。</p></section><section className="panel community-card"><div className="community-title"><h2>社区情绪</h2><span>检索样本</span></div>{data?.sentiment.status === 'ok' ? <><div className="community-ratios"><span>看多<strong className="up">{data.sentiment.bull}%</strong></span><span>观望<strong>{data.sentiment.neutral}%</strong></span><span>看空<strong className="down">{data.sentiment.bear}%</strong></span></div><div className="community-track"><span style={{ width: `${data.sentiment.bull}%` }} /><span style={{ width: `${data.sentiment.neutral}%` }} /><span style={{ width: `${data.sentiment.bear}%` }} /></div><p>{data.sentiment.sample_count} 条可核验帖子 · {data.sentiment.alert}</p><div className="keyword-tags">{data.sentiment.keywords.map(word => <span key={word}>{word}</span>)}</div><details><summary>查看样本来源</summary>{data.sentiment.posts.map(post => <a key={post.id} href={post.url} target="_blank" rel="noopener noreferrer">{post.title}<ExternalLink size={11} /></a>)}</details></> : <div className="community-empty"><Activity size={23} /><p>{data?.sentiment.status === 'empty' ? '没有取得日期可核验的独立帖子' : data?.sentiment.error ?? '尚未采集社区帖子'}</p><small>采集时勾选「含社区样本」。样本不足时不会生成看多 / 看空比例。</small></div>}<p className="source-note">{data?.sentiment.note ?? '使用 Tavily 搜索股吧 / 雪球公开帖子，无阅读和回复数时采用等权统计。'}</p></section><section className="research-assistant-card"><Sparkles size={22} /><span className="eyebrow">ASK A BETTER QUESTION</span><h2>把消息，放回上下文。</h2><p>让 AI 解释事实、推断和待核实条件，继续追问新闻可能的影响。</p><button disabled={!data} onClick={() => openAssistant()}>打开研究助手<ArrowRight size={15} /></button></section><button className="briefing-rail-link" onClick={briefing}><Bell size={18} /><span><strong>自选股早报</strong><small>查看汇总与订阅设置</small></span><ChevronRight size={15} /></button></aside>
  </div>;
}
